spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver # <-- Deprecated
    url: jdbc:mysql://localhost:3306/food_store?useSSL=false
    username: # username
    password: # password
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true

server:
  servlet:
    context-path: /update-query-builder/