spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver # <-- Deprecated
    url: jdbc:mysql://localhost:3306/food_store?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=utf-8&useUnicode=true
    username: # username
    password: # password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /update-query-builder/

logging:
  level:
    ROOT: DEBUG