spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_store?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=utf-8&useUnicode=true
    username: # username
    password: # password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /update-query-builder/

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG